feat!: support PostgreSQL as optional storage backend
cancervariants/disease-normalization pull request #116
Opened 2023-04-20 19:03 UTC by jsstevenson

2023-05-08 12:07 UTC, korikuzma requested changes
Overall looks great!

2023-05-08 12:07 UTC, korikuzma commented
@jsstevenson It also looks like there's some conflicts that need resolved before merging

2023-05-08 12:32 UTC, jsstevenson commented on disease/cli.py
> +        data_url = os.environ.get("DISEASE_NORM_REMOTE_DB_URL")
Yeah, I want to do one more iteration on the gene docs and then I'll start building out comparable stuff with disease and therapy

2023-05-08 12:33 UTC, korikuzma requested changes

2023-05-08 12:33 UTC, korikuzma commented on .github/workflows/github-actions.yml
> +      if: ${{ env.GENE_NORM_DB_URL == 'http://localhost:8000' }}
```suggestion
      if: ${{ env.DISEASE_NORM_DB_URL == 'http://localhost:8000' }}
```

2023-05-08 12:33 UTC, korikuzma commented on .github/workflows/github-actions.yml
> +      if: ${{ env.GENE_NORM_DB_URL == 'http://localhost:8000' }}
```suggestion
      if: ${{ env.DISEASE_NORM_DB_URL == 'http://localhost:8000' }}
```

2023-05-08 12:33 UTC, korikuzma commented on .github/workflows/github-actions.yml
> +      if: ${{ env.GENE_NORM_DB_URL != 'http://localhost:8000' }}
```suggestion
      if: ${{ env.DISEASE_NORM_DB_URL != 'http://localhost:8000' }}
```

2023-05-08 13:28 UTC, jsstevenson commented on .github/workflows/github-actions.yml
> +      if: ${{ env.GENE_NORM_DB_URL != 'http://localhost:8000' }}
f

2023-05-08 13:47 UTC, korikuzma approved these changes

2023-05-12 12:16 UTC, korikuzma approved these changes

2023-05-12 12:26 UTC, merged