cicd: update workflows/templates from template repo
cancervariants/disease-normalization pull request #196
Opened 2024-07-15 13:56 UTC by korikuzma

2024-07-15 23:14 UTC, jsstevenson requested changes

2024-07-15 23:14 UTC, jsstevenson commented on .github/workflows/stale.yaml
> +    uses: genomicmedlab/software-templates/.github/workflows/reusable-stale.yaml
@main etc etc

2024-07-15 23:30 UTC, korikuzma commented on .github/workflows/stale.yaml
> +    uses: genomicmedlab/software-templates/.github/workflows/reusable-stale.yaml
ugh another copy/paste from wrong repo 🤦

2024-07-16 06:52 UTC, jsstevenson approved these changes

2024-07-16 12:00 UTC, merged